model: fasterrcnn_resnet50_fpn_v2
data: data_configs/pi_detection.yaml
device: cuda
epochs: 31
workers: 4
batch: 4
lr: 3.019951720402016e-05
imgsz: 128
name: custom_training_3
vis_transformed: false
mosaic: 0.0
use_train_aug: false
cosine_annealing: false
weights: trained_model/new_5/last_model.pth
resume_training: true
square_training: false
world_size: 1
dist_url: env://
disable_wandb: true
sync_bn: false
amp: false
seed: 0
distributed: false
